// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaNcjeb4UJLXd6sOQIxPYZKdYfdTtzBOQ',
    appId: '1:769441006923:web:d160dbac45807f4301d4ce',
    messagingSenderId: '769441006923',
    projectId: 'sober-now-app',
    authDomain: 'sober-now-app.firebaseapp.com',
    storageBucket: 'sober-now-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR-Q-q23LW9jSH6Tf1RyVt5pf8MRr3VTg',
    appId: '1:769441006923:android:03319a4258ec16a501d4ce',
    messagingSenderId: '769441006923',
    projectId: 'sober-now-app',
    storageBucket: 'sober-now-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzx2uePkGi7alKhFNYt0wvqyBs9WFR0YQ',
    appId: '1:769441006923:ios:47a4ad1b8207dd4201d4ce',
    messagingSenderId: '769441006923',
    projectId: 'sober-now-app',
    storageBucket: 'sober-now-app.firebasestorage.app',
    iosBundleId: 'com.example.soberNowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzx2uePkGi7alKhFNYt0wvqyBs9WFR0YQ',
    appId: '1:769441006923:ios:47a4ad1b8207dd4201d4ce',
    messagingSenderId: '769441006923',
    projectId: 'sober-now-app',
    storageBucket: 'sober-now-app.firebasestorage.app',
    iosBundleId: 'com.example.soberNowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaNcjeb4UJLXd6sOQIxPYZKdYfdTtzBOQ',
    appId: '1:769441006923:web:ff4b73216a557c7f01d4ce',
    messagingSenderId: '769441006923',
    projectId: 'sober-now-app',
    authDomain: 'sober-now-app.firebaseapp.com',
    storageBucket: 'sober-now-app.firebasestorage.app',
  );
}
